---  # CFR experiment template config

DASHBOARD_TITLE: "CFR Experiment: Picture-in-Picture Normandy in 77 (beta)"
EXPERIMENT_SLUG: recommend-picture-in-picture-cfr-normandy
BRANCHES:
  - n4s_pip_control
  - n4s_pip_cfr
EXPERIMENT_BEGIN_DATE: 2020-05-06
MESSAGE_ID: N4S_PIP_CFR_MESSSAGE_NORMANDY
# CFR type could be either "cfrAddons" or "cfrFeatures". This decides the event
# of the recommendation adoption. I.e. "INSTALL" for "cfrAddons", "ENABLE" for
# "cfrFeatures"
CFR_TYPE: cfrFeatures
CFR_ADOPTION_EVENT:
  cfrFeatures: ENABLE
  cfrAddons: INSTALL
