---  # CFR experiment template config

DASHBOARD_TITLE: "CFR Experiment: Homepage Remediation Search Value (v2) in 83"
EXPERIMENT_SLUG: message-homepage-remediation-v2-search-value-props-exper-release-83
BRANCHES:
  - treatment-a
  - treatment-b
  - treatment-c
  - control
EXPERIMENT_BEGIN_DATE: 2020-11-18
MESSAGE_ID: N4S_PIP_CFR_MESSSAGE_NORMANDY
# CFR type could be either "cfrAddons" or "cfrFeatures". This decides the event
# of the recommendation adoption. I.e. "INSTALL" for "cfrAddons", "ENABLE" for
# "cfrFeatures"
CFR_TYPE: cfrFeatures
CFR_ADOPTION_EVENT:
  cfrFeatures: ENABLE
  cfrAddons: INSTALL
