---  # CFR experiment template config

DASHBOARD_TITLE: "CFR Experiment: Picture-in-Picture Normandy in 77 (beta)"
EXPERIMENT_SLUG: bug-1635199-message-recommend-picture-in-picture-cfr-beta-77-77
BRANCHES:
  - n4s_pip_control
  - n4s_pip_cfr
EXPERIMENT_BEGIN_DATE: 2020-05-05
MESSAGE_ID: N4S_PIP_CFR_MESSSAGE
# CFR type could be either "cfrAddons" or "cfrFeatures". This decides the event
# of the recommendation adoption. I.e. "INSTALL" for "cfrAddons", "ENABLE" for
# "cfrFeatures"
CFR_TYPE: cfrFeatures
CFR_ADOPTION_EVENT:
  cfrFeatures: ENABLE
  cfrAddons: INSTALL
