---  # CFR template config

DASHBOARD_TITLE: "CFR Experiment: Firefox Better Web (77)"
BUCKET_ID: CFR_FBW_MARCH_PROMOTION
# CFR type could be either "cfrAddons" or "cfrFeatures". This decides the event
# of the recommendation adoption. I.e. "INSTALL" for "cfrAddons", "ENABLE" for
# "cfrFeatures"
CFR_TYPE: cfrFeatures
CFR_ADOPTION_EVENT:
  cfrFeatures: ENABLE
  cfrAddons: INSTALL
