---  # CFR template config

DASHBOARD_TITLE: "CFR Exeperiment: Picture-in-Picture (beta)"
EXPERIMENT_SLUG: bug-1635199-message-recommend-picture-in-picture-cfr-beta-77-77
BRANCHES:
  - control
  - variant_1
EXPERIMENT_BEGIN_DATE: 2020-05-04
MESSAGE_ID: N4S_PIP_CFR_MESSAGE
