---  # CFR template config

DASHBOARD_TITLE: "CFR Exeperiment: Facebook Container A/A Test (beta)"
EXPERIMENT_SLUG: cfr_xman_smoke_test
BRANCHES:
  - control
  - variant_1
EXPERIMENT_BEGIN_DATE: 2020-04-30
MESSAGE_ID: FACEBOOK_CONTAINER_3_72
