---  # Onboarding template config

DASHBOARD_TITLE: |
  "Messaging System Experiment: about:welcome Pull Factor in Firefox 76"
EXPERIMENT_SLUG: bug-1637316-message-aboutwelcome-pull-factor-reinforcement-76-rel-release-76-77
EXPERIMENT_BEGIN_DATE: 2020-05-14
BRANCHES:
  - slug: control
    cards:
      - TRAILHEAD_CARD_2
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-variation-b
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-variation-c
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-variation-d
    cards:
      - TRAILHEAD_CARD_2
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
TRIPLET_ID_LIST:
  - TRAILHEAD_CARD_2
  - TRAILHEAD_CARD_3
  - TRAILHEAD_CARD_4
  - TRAILHEAD_CARD_12
CARD_ID_MAP:
  TRAILHEAD_CARD_2: Sync
  TRAILHEAD_CARD_3: Monitor
  TRAILHEAD_CARD_4: Private Browsing
  TRAILHEAD_CARD_12: Data Promise
