---  # Onboarding template config

DASHBOARD_TITLE: |
  "Messaging System Experiment: Multi-Stage about:welcome in Firefox beta 78"
EXPERIMENT_SLUG: bug-1644521-message-multi-stage-aboutwelcome-v1-78-beta-v2-beta-78-79
EXPERIMENT_BEGIN_DATE: 2020-06-12
BRANCHES:
  - slug: control
    cards:
      - TRAILHEAD_CARD_2
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-static
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-dynamic
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
TRIPLET_ID_LIST:
  - TRAILHEAD_CARD_2
  - TRAILHEAD_CARD_3
  - TRAILHEAD_CARD_4
  - TRAILHEAD_CARD_12
CARD_ID_MAP:
  TRAILHEAD_CARD_2: Sync
  TRAILHEAD_CARD_3: Monitor
  TRAILHEAD_CARD_4: Private Browsing
  TRAILHEAD_CARD_12: Data Promise
