---  # Onboarding template config

DASHBOARD_TITLE: |
  "Messaging System Experiment: Multi-Stage about:welcome V2 in Firefox 79"
EXPERIMENT_SLUG: bug-1653032-message-multi-stage-aboutwelcome-v2-79-release-release-79-80
EXPERIMENT_BEGIN_DATE: 2020-08-04
BRANCHES:
  - slug: control
    cards:
      - TRAILHEAD_CARD_2
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-a
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-b
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
  - slug: treatment-c
    cards:
      - TRAILHEAD_CARD_12
      - TRAILHEAD_CARD_3
      - TRAILHEAD_CARD_4
TRIPLET_ID_LIST:
  - TRAILHEAD_CARD_2
  - TRAILHEAD_CARD_3
  - TRAILHEAD_CARD_4
  - TRAILHEAD_CARD_12
CARD_ID_MAP:
  TRAILHEAD_CARD_2: Sync
  TRAILHEAD_CARD_3: Monitor
  TRAILHEAD_CARD_4: Private Browsing
  TRAILHEAD_CARD_12: Data Promise
