---  # Whats-new-panel template config

DASHBOARD_TITLE: |
  Messaging System: What's New Panel in Firefox 84
FIREFOX_VERSON: 84
RELEASE_BEGIN_DATE: 2020-12-14
RELEASE_END_DATE: 2021-01-26
WNP_BADGE_ID: WHATS_NEW_BADGE_84
PANEL_MESSAGE_IDS:
  # The order matters, it should have the same order as the `bucket_id` in the
  # panel impression ping
  - WHATS_NEW_COOKIES_PROTECTION_80
  - WHATS_NEW_MEDIA_SESSION_82
  - WHATS_NEW_SEARCH_SHORTCUTS_84
